### ISSUE TITLE
Update README with examples

### ISSUE THREAD

**Issue by paulvi** [tesla/tesla-ide#1]
Is there Eclipse built with this solution that can be downloaded?

Or is there working script?

**Comment by jvanzyl** [comment]
I updated the README.md file. But you edit your product.yml file, run ./product.rb and then you can run mvn clean package and it will produce a distribution for you in io.tesla.ide.rcp.product/target.

You will need to change the environments that you want the RCP application built for as currently I only  build it for OSX.

**Comment by paulvi** [comment]
Should it work on Windows?

**Comment by jvanzyl** [comment]
Sure, just take a look at https://github.com/tesla/tesla-ide/blob/master/product.yml#L18 and add "windows" as an environment, run ./product.rb and mvn clean package and it should make the windows distro as well.
